### ISSUE TITLE
Password recovery errors on submission of new password

### ISSUE THREAD

**Issue by davidnewcomb** [mishamx/yii-user#61]
What steps will reproduce the problem?
1. Click "Lost Password?".
2. Enter user name, click Recovery, get email.
3. Enter link from email.
4. Enter new password (twice), click Save.

Error (attached) is presented and page fails to load.
Tried entering the activation link again and you get the message "Incorrect recovery link."

Password appears to have been changed.

Latest source from github at the time or reporting.

![submit-password-recovery](https://f.cloud.github.com/assets/951359/1255312/36ebca52-2b83-11e3-959e-7b5ed00824c1.jpg)

**Comment by asommariva** [comment]
Hi all! I solved in a different way.

Just added the following line:
```
Yii::app()->user->id = $find->id;
```

Before this line in RecoveryController.php:
```
$find->save();
```

After that, you are logged in. Is this a correct solution? Thanks!!

**Comment by asommariva** [comment]
I also used @davidnewcomb's solution for a similar error when activating a new account.

**Comment by mishamx** [comment]
Fixed 0176ce7
